
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry txtHost;

	private global::Gtk.Entry textPort;

	private global::Gtk.Entry txtDb;

	private global::Gtk.Entry txtUser;

	private global::Gtk.Entry txtPassword;

	private global::Gtk.Label label3;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label5;

	private global::Gtk.Label label4;

	private global::Gtk.Button button3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtHost = new global::Gtk.Entry();
		this.txtHost.CanFocus = true;
		this.txtHost.Name = "txtHost";
		this.txtHost.IsEditable = true;
		this.txtHost.InvisibleChar = '•';
		this.fixed1.Add(this.txtHost);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtHost]));
		w1.X = 197;
		w1.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.textPort = new global::Gtk.Entry();
		this.textPort.CanFocus = true;
		this.textPort.Name = "textPort";
		this.textPort.IsEditable = true;
		this.textPort.InvisibleChar = '•';
		this.fixed1.Add(this.textPort);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.textPort]));
		w2.X = 199;
		w2.Y = 126;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtDb = new global::Gtk.Entry();
		this.txtDb.CanFocus = true;
		this.txtDb.Name = "txtDb";
		this.txtDb.IsEditable = true;
		this.txtDb.InvisibleChar = '•';
		this.fixed1.Add(this.txtDb);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtDb]));
		w3.X = 200;
		w3.Y = 180;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtUser = new global::Gtk.Entry();
		this.txtUser.CanFocus = true;
		this.txtUser.Name = "txtUser";
		this.txtUser.IsEditable = true;
		this.txtUser.InvisibleChar = '•';
		this.fixed1.Add(this.txtUser);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtUser]));
		w4.X = 200;
		w4.Y = 244;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPassword = new global::Gtk.Entry();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.InvisibleChar = '•';
		this.fixed1.Add(this.txtPassword);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtPassword]));
		w5.X = 202;
		w5.Y = 311;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Database:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w6.X = 130;
		w6.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Server:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w7.X = 135;
		w7.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Port:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w8.X = 136;
		w8.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w9.X = 127;
		w9.Y = 319;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("User:");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w10.X = 133;
		w10.Y = 252;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Test Connection");
		this.fixed1.Add(this.button3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3]));
		w11.X = 253;
		w11.Y = 365;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 412;
		this.DefaultHeight = 424;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler(this.btn_TestConnection_Click);
	}
}
